site_name: grid-fit Documentation
site_description: Documentation for grid-fit - fast grid interpolation
site_author: Rachel Alcraft
repo_url: https://github.com/rae-gh/grid-fit
repo_name: alcraft/grid-fit

nav:
  - Home: index.md
  - Bindings: bindings.md
  - Development: development.md
  - Benchmarking: benchmarking.md
  - Multivariate Interpolation PDF: MultivariateInterpolation.pdf

theme:
  name: material
  palette:
    primary: blue
  favicon: gridfit_icon.png
  logo: gridfit_icon.png


plugins:
  - search
  - mermaid2


markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.progressbar
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.magiclink




