site_name: grid-fit Documentation
nav:
  - Home: index.md
  - Bindings: bindings.md
  - Development: development.md
  - Benchmarking: benchmarking.md
theme:
  name: material
  palette:
    primary: blue
  favicon: gridfit_icon.png
  logo: gridfit_icon.png 

plugins:
  - search
  - mermaid2

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.progressbar
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.magiclink
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_javascript:
  - https://unpkg.com/mermaid@10.4.0/dist/mermaid.min.js


