site_name: grid-fit Documentation
nav:
  - Home: index.md
  - Bindings: bindings.md
  - Development: development.md
  - Benchmarking: benchmarking.md
theme:
  name: material
  palette:
    primary: blue
  favicon: gridfit_icon.png
  logo: gridfit_icon.png 

plugins:
  - search
  - mermaid2

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.details


